swift_version: 2.2
output: ./
source_directory: NEKit/
readme: NEKit/README.md
author: Zhuhao Wang
module: NEKit
github_url: https://github.com/zhuhaow/NEKit
min_acl: internal

custom_categories:
  - name: Proxy Server
    children:
    - ProxyServer
    - GCDProxyServer
    - GCDSOCKS5ProxyServer
  
  - name: Raw Socket
    children:
    - RawTCPSocketProtocol
    - RawTCPSocketDelegate
    - GCDTCPSocket
    - NWTCPSocket
    - TUNTCPSocket
    - RawSocketFactory
    - SocketBaseType
    - SocketTag
    - NWUDPSocket
    - NWUDPSocketDelegate
  
  - name: Rule
    children:
    - Rule
    - AllRule
    - DirectRule
    - CountryRule
    - ListRule
    - DNSSessionMatchType
    - DNSSessionMatchResult
