swift_version: 2.2
output: ./
source_directory: NEKit/
readme: NEKit/README.md
author: Zhuhao Wang
module: NEKit
github_url: https://github.com/zhuhaow/NEKit
min_acl: internal

custom_categories:
  - name: Proxy Server
    children:
    - ProxyServer
    - GCDProxyServer
    - GCDSOCKS5ProxyServer
  
  - name: Raw Socket
    children:
    - RawTCPSocketProtocol
    - RawTCPSocketDelegate
    - GCDTCPSocket
    - NWTCPSocket
    - TUNTCPSocket
    - RawSocketFactory
    - SocketBaseType
    - SocketTag
    - NWUDPSocket
    - NWUDPSocketDelegate
  
  - name: Socket
    children:
    - SocketProtocol
    - SocketDelegate
  
  - name: Proxy Socket
    children:
    - ProxySocketProtocol
    - ProxySocket
    - DirectProxySocket
    - SOCKS5ProxySocket
  
  - name: Adapter Socket
    children:
    - AdapterSocket
    - DirectAdapter
    - HTTPAdapter
    - SecuredHTTPAdapter
    - ShadowsocksAdapter
    - SpeedAdapter
  
  - name: Adapter Socket Factory
    children:
    - AdapterFactoryManager
    - AdapterFactoryProtocol
    - ServerAdapterFactory
    - AuthenticationAdapterFactory
    - DirectAdapterFactory
    - ShadowsocksAdapterFactory
    - HTTPAdapterFactory
    - SecureHTTPAdapterFactory
    - SpeedAdapterFactory
  
  - name: Rule
    children:
    - Rule
    - AllRule
    - DirectRule
    - CountryRule
    - ListRule
    - DNSSessionMatchType
    - DNSSessionMatchResult
    
  - name: IP stack
    children:
    - TUNInterface
    - IPStackProtocol
    - TCPStack
    - DNSServer
  
  - name: Utilities
    children:
    - BinaryDataScanner
    - Atomic
    - StreamScanner
    - Checksum
