port: 9090
adapter:
  - id: goagentx
    type: HTTP
    host: 123.123.123.123
    port: 8016
  - id: speed
    type: SPEED
    adapters:
      - id: goagentx
        delay: 300
      - id: direct
        delay: 0
rule:
  - type: country
    country: CN
    match: true
    adapter: direct
  - type: list
    file: ~/.NEKitDemo/direct
    adapter: direct
  - type: all
    adapter: speed
