language: objective-c
osx_image: xcode7.3

cache:
  directories:
    - Carthage

install:
  - brew update && brew install swiftlint
  - bin/bootstrap-if-needed
  
script:
  - xctool -project NEKit.xcodeproj -scheme "NEKit-macOS" -sdk macosx10.11 -arch x86_64 build
  - xctool -project NEKit.xcodeproj -scheme "NEKit-iOS" -sdk iphoneos9.3 -arch arm64 build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

after_success:
  - ./scripts/build_docs.sh

